title: Chaitanya Inamdar
#logo: /assets/img/headshot_circle.png
#description: text below image
# Custom Links
linkedin: https://www.linkedin.com/in/chaitanya-inamdar98/
show_downloads: true
theme: jekyll-theme-minimal
